import { Round } from './types'

export const ROUNDS: Round[] = [
  {
    title: 'WINTER OLYMPIC HISTORY',
    questions: [
      { question: 'In which year were the first Winter Olympic Games held?', answer: '1924' },
      { question: 'Which city hosted the inaugural Winter Olympics in 1924?', answer: 'Chamonix' },
      { question: 'How many sports were featured at the first Winter Olympics?', answer: '9' },
      { question: 'Which country has won the most Winter Olympic gold medals of all time?', answer: 'Norway' },
      { question: 'In what year did the Winter and Summer Olympics split into separate four-year cycles?', answer: '1994' },
      { question: 'Which city hosted the Winter Olympics twice, in 1932 and 1980?', answer: 'Lake Placid' },
      { question: 'Who lit the cauldron at the 1994 Lillehammer Winter Olympics opening ceremony?', answer: 'Crown Prince Haakon' },
      { question: 'Which country hosted the 2022 Winter Olympics?', answer: 'China' },
      { question: 'How many rings are on the Olympic flag?', answer: '5' },
      { question: 'Which Winter Olympics was the first to allow professional athletes?', answer: 'Calgary 1988' },
    ],
  },
  {
    title: 'ALPINE & SNOW SPORTS',
    questions: [
      { question: 'How many disciplines are contested in Alpine skiing at the Olympics?', answer: '5' },
      { question: 'What is the maximum number of ski runs allowed in Olympic slalom?', answer: '2' },
      { question: 'Which country invented the sport of biathlon as an Olympic discipline?', answer: 'Norway' },
      { question: 'In ski jumping, what is the name of the starting position used on the hill?', answer: 'In-run position' },
      { question: 'How many shooting targets must a biathlete hit in each range stop?', answer: '5' },
      { question: 'What material are modern Olympic cross-country ski poles typically made from?', answer: 'Carbon fibre' },
      { question: 'In freestyle skiing aerials, what score multiplier is applied for difficulty?', answer: 'Degree of difficulty' },
      { question: 'How long is the women\'s Olympic biathlon pursuit race?', answer: '10 km' },
      { question: 'What is the minimum gradient for an Olympic downhill course?', answer: '800m vertical drop' },
      { question: 'Which ski event combines downhill and slalom disciplines?', answer: 'Alpine Combined' },
    ],
  },
  {
    title: 'ICE SPORTS & SKATING',
    questions: [
      { question: 'How many players are on the ice per team in Olympic ice hockey?', answer: '6' },
      { question: 'What is the name of the quadruple-rotation jump in figure skating?', answer: 'Quadruple jump' },
      { question: 'How long is an Olympic speed skating long track?', answer: '400 metres' },
      { question: 'What is the weight of the stone used in Olympic curling?', answer: '19.96 kg (44 lbs)' },
      { question: 'In short track speed skating, what distance is the most popular Olympic event?', answer: '1000 m' },
      { question: 'How many ends are played in an Olympic curling match?', answer: '10' },
      { question: 'Which element is mandatory in the Olympic figure skating free skate for pairs?', answer: 'Throw jump' },
      { question: 'In speed skating, what is a "flying start"?', answer: 'Mass start with no stagger' },
      { question: 'What temperature is Olympic ice hockey ice kept at?', answer: '-5 to -9°C (23–16°F)' },
      { question: 'How many sheets of ice are used in Olympic curling competition simultaneously?', answer: '4' },
    ],
  },
  {
    title: 'BOBSLED, LUGE & SKELETON',
    questions: [
      { question: 'In which direction does a skeleton athlete travel down the track?', answer: 'Head first, face down' },
      { question: 'How many crew members are in an Olympic four-man bobsled?', answer: '4' },
      { question: 'What is the top speed typically reached in Olympic luge?', answer: 'Over 140 km/h' },
      { question: 'Which of the sliding sports was added most recently to the Olympics?', answer: 'Skeleton (2002)' },
      { question: 'In luge, athletes steer primarily using which body part?', answer: 'Calves and shoulders' },
      { question: 'What is the name of the starting position area in bobsled?', answer: 'Start house' },
      { question: 'How many runs do Olympic luge athletes complete in competition?', answer: '4' },
      { question: 'Which country dominated bobsled at the Winter Olympics for most of the 20th century?', answer: 'Switzerland' },
      { question: 'What material are modern competition luge sleds primarily made from?', answer: 'Fibreglass and carbon fibre' },
      { question: 'In Olympic bobsled, how is time measured for each run?', answer: 'To the thousandth of a second' },
    ],
  },
  {
    title: 'MILAN–CORTINA 2026',
    questions: [
      { question: 'Which two Italian cities co-host the 2026 Winter Olympics?', answer: 'Milan and Cortina d\'Ampezzo' },
      { question: 'In which year was the 2026 Winter Olympics host city selected?', answer: '2019' },
      { question: 'What is the motto of the Milan–Cortina 2026 Winter Olympics?', answer: 'Dreams Are Forever' },
      { question: 'How many sports are on the programme for Milan–Cortina 2026?', answer: '16' },
      { question: 'Which new discipline makes its Olympic debut at Milan–Cortina 2026?', answer: 'Flag football (not winter); correct answer: Ski mountaineering' },
      { question: 'Which arena will host ice hockey at Milan–Cortina 2026?', answer: 'Mediolanum Forum' },
      { question: 'What is the name of the Milan–Cortina 2026 mascot?', answer: 'Tina' },
      { question: 'In what month does the Milan–Cortina 2026 Olympics begin?', answer: 'February' },
      { question: 'What river flows through the host city of Milan?', answer: 'Navigli canals (Ticino/Lambro/Olona)' },
      { question: 'How many athletes are expected to compete at Milan–Cortina 2026?', answer: 'Approximately 2,900' },
    ],
  },
]
